### ISSUE TITLE
Determine data licence

### ISSUE THREAD

**Issue by vicchi** [woeplanet/woeplanet-data#1]
Historically GeoPlanet Data was released under CC-BY 3.0. Which licence should we use for Woeplanet?

The _new_ CDLA Permissive licence is already proposed for Who's On First and would seem suitable. The OSMF have also determined that CDLA Permissive is compatible with CC-BY, see https://wiki.osmfoundation.org/wiki/CDLA_permissive_compatibility

My thinking is to keep the original CC-BY licence statement for the original GeoPlanet Data and to (re)licence under CDLA for Woeplanet as a data corpus.

Thoughts?

**Comment by straup** [comment]
I agree.

**Comment by vicchi** [comment]
CDLA Permissive it is then
